### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by 0xidant** [shubhamaggarwal/youtube-mp3-downloader#4]
OS: `Ubuntu 20.04`
Python version: `3.8.5`
pip3 version: `20.3.1`
installed as: `sudo pip3 install youtube-mp3-downloader`

error:
```py
mp3 hotel california

We have got your stuff. Meanwhile you can practice breathing in and out: 
Results found = 0
Sorry, no results found.
Traceback (most recent call last):
  File "/home/usr/.local/bin/mp3", line 133, in <module>
    mp3downloader()
  File "/home/usr/.local/bin/mp3", line 88, in mp3downloader
    filename, video_url = scrape()
TypeError: cannot unpack non-iterable NoneType object


```

**Comment by danielflachica** [comment]
I have the same issue.

OS: `MacOS 11.2.3`
Python version: `3.8.5`
pip3 version: `20.2.3`
installed as: `pip3 install youtube-mp3-downloader`

error: 
```
mp3 hotel california                                                  1 ✘  8s   04:03:19 PM 

We have got your stuff. Meanwhile you can practice breathing in and out:
Results found = 0
Sorry, no results found.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/mp3", line 133, in <module>
    mp3downloader()
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/mp3", line 88, in mp3downloader
    filename, video_url = scrape()
TypeError: cannot unpack non-iterable NoneType object
```
